// Code generated by tygo. DO NOT EDIT.

//////////
// source: catalog.go

/**
 * KnobType identifies the declared value shape for a knob. The Store layer
 * stores values as opaque JSON-encoded strings; the catalog owns type/range
 * validation on the way in and decode on the way out.
 */
export type KnobType = string;
export const KnobInt: KnobType = "int";
export const KnobFloat: KnobType = "float";
export const KnobString: KnobType = "string";
export const KnobEnum: KnobType = "enum";
export const KnobMultiselect: KnobType = "multiselect";
/**
 * KnobDef describes one knob in the v1 catalog. Slider fields are optional
 * and used only by numeric knobs for UI hinting; EnumValues constrains enums.
 * Default is the system-tier value returned when no explicit entry exists at
 * task / manifest / product scope.
 */
export interface KnobDef {
  key: string;
  type: KnobType;
  slider_min?: number /* float64 */;
  slider_max?: number /* float64 */;
  slider_step?: number /* float64 */;
  enum_values?: string[];
  default: any;
  description: string;
  unit?: string;
}
