// Code generated by tygo. DO NOT EDIT.
// GENERATED FILE — DO NOT EDIT. Run `make types` to regenerate from Go.

//////////
// source: dependencies.go

/**
 * Dep is the denormalized row UI + MCP callers want when listing deps
 * or dependents: id + marker + title + current status is enough to
 * render without a second lookup per row. Matches the Dep shape in
 * manifest.Dep so consumers can reuse render helpers across tiers.
 */
export interface Dep {
  id: string;
  marker: string;
  title: string;
  status: string;
  created_at: string;
  created_by: string;
}

//////////
// source: store.go

/**
 * Product is a top-level organizational entity: Peer → Product → Manifest → Task.
 */
export interface Product {
  id: string;
  marker: string;
  title: string;
  description: string;
  status: string; // draft, open, closed, archive
  source_node: string; // peer UUID
  tags: string[];
  created_at: string;
  updated_at: string;
  /**
   * Computed — aggregated from manifests → tasks → task_runs
   */
  total_manifests: number /* int */;
  total_tasks: number /* int */;
  total_turns: number /* int */;
  total_cost: number /* float64 */;
}
/**
 * Store manages product persistence.
 */
export interface Store {
}
