// Code generated by tygo. DO NOT EDIT.
// GENERATED FILE — DO NOT EDIT. Run `make types` to regenerate from Go.

//////////
// source: host_metrics.go

/**
 * HostMetricsSample is one CPU/RSS reading of the serve process. The
 * sampler stamps a sample into every currently-attached task, so the
 * per-run Run Stats card can overlay host load on the same timeline as
 * the model's own turn/cost/actions lines.
 */
export interface HostMetricsSample {
  ts: string;
  cpu_pct: number /* float64 */;
  rss_mb: number /* float64 */;
  /**
   * Live task counters captured at the same tick as host CPU/RSS.
   * Feeds the Run Stats card's 5-aligned-sparkline layout — same X-axis
   * as CPU/RSS. Populated by a runner-supplied TaskStatFn closure.
   */
  cost_usd: number /* float64 */;
  turns: number /* int */;
  actions: number /* int */;
}
/**
 * TaskStatFn pulls the attached task's live counters at sample time. The
 * runner supplies it at Attach (closes over the RunningTask pointer so
 * it sees live updates).
 */
export type TaskStatFn = any;
/**
 * HostMetrics is the summary rolled up from a task's samples on Detach.
 * Persisted as denormalised columns on task_runs so dashboards can sort
 * / filter without scanning the samples table.
 */
export interface HostMetrics {
  PeakCPUPct: number /* float64 */;
  AvgCPUPct: number /* float64 */;
  PeakRSSMB: number /* float64 */;
}
/**
 * HostSampler polls the serve process for CPU% + RSS every Interval and
 * attributes each reading to every attached task. Tasks Attach at spawn
 * and Detach at completion; Detach returns the accumulated samples and
 * the rolled-up HostMetrics for persistence.
 * Cheap by design: one `ps -o %cpu=,rss= -p <pid>` fork every Interval
 * (default 5s). Zero when no tasks are attached — fanout is a no-op.
 * attachedTask bundles the per-task sample buffer with the callback the
 * sampler invokes at each tick to read live cost/turns/actions.
 */
export interface HostSampler {
}

//////////
// source: manifest_activation.go

/**
 * manifestBlockPrefix is the canonical prefix both Store.Create and
 * the scheduler pre-dispatch gate (after #97) write into block_reason
 * when seeding a task as 'waiting' due to an unsatisfied manifest.
 * FlipManifestBlockedTasks filters on it so a task that ended up in
 * 'waiting' for a different reason (e.g. task-level dep not met) does
 * not get accidentally flipped by a manifest-level activation.
 */
/**
 * legacyManifestBlockPrefix is the prefix the scheduler's
 * pre-dispatch gate wrote BEFORE #97 normalized it. Kept so the
 * activation filter still catches waiting tasks that were seeded
 * under the old format — rows in the wild today were written with
 * "blocked by manifest <marker> (<title>)". Removable once a DB
 * audit confirms no row still has this prefix.
 */

//////////
// source: metrics.go

/**
 * CostAggregation holds aggregated cost data for a time period.
 */
export interface CostAggregation {
  period: string;
  tasks: number /* int */;
  runs: number /* int */;
  turns: number /* int */;
  cost: number /* float64 */;
  budget: number /* float64 */;
}
/**
 * CostDrillDownEntry represents individual task runs for a specific date.
 */
export interface CostDrillDownEntry {
  run_id: number /* int */;
  task_id: string;
  task_marker: string;
  task_title: string;
  manifest_id: string;
  agent: string;
  run_number: number /* int */;
  status: string;
  actions: number /* int */;
  cost_usd: number /* float64 */;
  turns: number /* int */;
  duration_sec: number /* int */;
  started_at: string;
  completed_at: string;
}
/**
 * CostTrendSummary holds summary cost data for trend cards.
 */
export interface CostTrendSummary {
  today: number /* float64 */;
  this_week: number /* float64 */;
  this_month: number /* float64 */;
  avg_30d: number /* float64 */;
}
/**
 * ProductivityMetrics holds the calculated productivity score and its components.
 */
export interface ProductivityMetrics {
  /**
   * Overall score (0-100)
   */
  score: number /* int */;
  grade: string; // A, B, C, D, F
  /**
   * Positive signals
   */
  tasks_completed: number /* int */;
  first_attempt_pass: number /* int */; // completed on run 1
  lines_committed: number /* int */; // insertions from watcher git_details
  files_changed: number /* int */;
  watcher_pass_rate: number /* int */; // percentage
  total_actions: number /* int */;
  /**
   * Negative signals
   */
  tasks_failed: number /* int */;
  rework_runs: number /* int */; // tasks with run_count > 1
  amnesia_count: number /* int */;
  watcher_failures: number /* int */;
  /**
   * Efficiency
   */
  avg_turns_per_task: number /* float64 */;
  cost_per_completion: number /* float64 */;
  total_cost: number /* float64 */;
  total_turns: number /* int */;
  /**
   * Trend (last 7 days, one score per day)
   */
  trend: DailyProductivity[];
  /**
   * Period
   */
  period: string; // today, week, month
}
/**
 * DailyProductivity holds productivity data for a single day.
 */
export interface DailyProductivity {
  date: string;
  score: number /* int */;
  tasks_completed: number /* int */;
  tasks_failed: number /* int */;
  lines_committed: number /* int */;
  cost: number /* float64 */;
}

//////////
// source: migrate.go

/**
 * migrationMarkerKey is the settings row key that records completion of the
 * one-shot tasks.max_turns → settings(task-scope) migration. Stored at
 * (scope_type='system', scope_id=''), consistent with the _retry_count
 * underscore-prefix convention established by M4-T12.
 */

//////////
// source: pricing.go

/**
 * Usage holds the token counts we bill on. Fields mirror the stream-json
 * message.usage shape emitted by Claude Code.
 */
export interface Usage {
  InputTokens: number /* int */;
  OutputTokens: number /* int */;
  CacheCreationTokens: number /* int */;
  CacheReadTokens: number /* int */;
}
/**
 * ModelRates holds the per-million-token rates for a model family. Values are
 * the list-price defaults; real billing is calibrated per model by
 * Store.CalibrateModelPricing against the authoritative total_cost_usd
 * emitted by Claude Code in the terminal result event.
 */
export interface ModelRates {
  InputPerMTok: number /* float64 */;
  OutputPerMTok: number /* float64 */;
  CacheWritePerMTok: number /* float64 */;
  CacheReadPerMTok: number /* float64 */;
}
/**
 * ModelPricing is what we persist per model — a single scalar that scales
 * the default rate table to match the actual total_cost_usd reported by the
 * terminal result event. EMA-updated on every completed run.
 */
export interface ModelPricing {
  Model: string;
  Multiplier: number /* float64 */;
  Samples: number /* int */;
  UpdatedAt: string;
}
/**
 * calibrationAlpha is the EMA weight applied to a new sample. 0.3 gives the
 * latest run moderate influence without losing history — the multiplier
 * settles within ~10 runs if pricing is stable.
 */

//////////
// source: product_activation.go

/**
 * productBlockPrefix is the literal prefix Store.Create writes into
 * block_reason when seeding a task as 'waiting' due to an unsatisfied
 * product-level dependency. FlipProductBlockedTasks filters on it so
 * tasks waiting for a different reason (task-level or manifest-level
 * dep) don't get swept up by product-close propagation.
 */
/**
 * ProductReadinessChecker is the hook task.Store consults to decide
 * whether a new task's product has all its product-level dependencies
 * satisfied. Mirrors ManifestReadinessChecker from #77. Wired in
 * node.go.
 */
export type ProductReadinessChecker = any;

//////////
// source: repository.go

/**
 * ManifestReadinessChecker is the hook task.Store consults to decide
 * whether a new task's manifest is currently satisfied (i.e. every one
 * of its manifest-level dependencies is in a terminal status). If a
 * manifest is unsatisfied, tasks created against it are seeded in
 * 'waiting' with a populated block_reason so the operator sees which
 * manifest is blocking them.
 * Implemented by manifest.Store; wired via an adapter in node.go.
 * Optional — a nil checker skips the check, which preserves pre-fix
 * behavior and keeps unit tests standalone.
 */
export type ManifestReadinessChecker = any;
/**
 * DepHistoryEntry is one row of the SCD Type 2 task_dependency table.
 * Rows are the full history of the task's dep relationship in
 * chronological order. The current/active row has ValidTo == "".
 */
export interface DepHistoryEntry {
  id: number /* int */;
  task_id: string;
  depends_on: string; // empty = dep cleared in this revision
  valid_from: string;
  valid_to: string; // empty = currently active
  changed_by: string;
  reason: string;
}
/**
 * PendingActionRequest holds a task ID + requested action.
 */
export interface PendingActionRequest {
  TaskID: string;
  Action: string;
}
/**
 * PricingVersion stamps the pricing table identity used to compute cost_usd
 * for a task_runs row. Increment whenever internal/task/pricing.go's rate
 * table changes so the future Unified Cost Tracking product (019dab45-d8f)
 * can re-cost historical rows under the right table — or flag drift when
 * today's rates differ from when the row was originally written.
 */
export const PricingVersion = "v1-2026-04";

//////////
// source: review.go

/**
 * ReviewComment is the trimmed view task.Store needs of a review
 * comment row. comments.Comment carries more fields than TaskReviewStatus
 * needs, so we hand-roll a narrower struct here to avoid an import
 * on internal/comments.
 */
export interface ReviewComment {
  ID: string;
  Type: string; // "review_rejection" | "review_approval"
  Author: string;
  Body: string;
  CreatedAt: string;
}
/**
 * ReviewWriter is what task.Store calls to append a review
 * comment (rejection or approval) to a task. node.go wires an adapter
 * around comments.Store that satisfies this interface — keeps task
 * free of an internal/comments import so the two packages stay
 * independently testable.
 */
export type ReviewWriter = any;
/**
 * ReviewReader lists review-type comments for a task. Same injection
 * pattern: node.go bridges comments.Store.ListByTarget to this shape.
 */
export type ReviewReader = any;
/**
 * TaskReviewStatus is the derived view of a task's review state.
 * NeedsRework is true iff the latest review-type comment (by
 * created_at) is a rejection. An approval clears it; a subsequent
 * rejection re-sets it.
 */
export interface TaskReviewStatus {
  needs_rework: boolean;
  has_approval: boolean;
  latest_rejection_at?: string;
  latest_rejection_reason?: string;
  latest_rejection_by?: string;
  latest_approval_at?: string;
  latest_approval_by?: string;
}

//////////
// source: runner.go

/**
 * RunningTask tracks an actively executing task.
 */
export interface RunningTask {
  task_id: string;
  marker: string;
  title: string;
  manifest: string;
  /**
   * ProductID is the resolved product scope for the task — empty for
   * standalone tasks with no manifest. Used by the per-product dispatch cap.
   */
  product_id: string;
  agent: string;
  pid: number /* int */;
  paused: boolean;
  started_at: string;
  actions: number /* int */;
  lines: number /* int */;
  last_line: string;
  /**
   * CumulativeCostUSD tracks running cost parsed from stream-json events.
   * Updated by the reader goroutine as each event arrives so the mid-run
   * cost cap has a live value to compare against.
   */
  cumulative_cost_usd: number /* float64 */;
  /**
   * Model is the model id reported by the first assistant event — used to
   * pick a pricing table and for calibration after the run.
   */
  model: string;
}
/**
 * Runner manages task execution — spawning agents and tracking running tasks.
 * Every knob that shapes a task's execution (max_parallel, max_turns, timeout,
 * model, agent, temperature, reasoning_effort, max_cost_usd, daily_budget_usd,
 * retry_on_failure, approval_mode, allowed_tools) is resolved per-task at
 * Execute time via the settings Resolver: it walks task → manifest → product
 * → system so two products can have different caps. Standalone tasks (no
 * manifest/product) fall through to the catalog system defaults.
 */
export interface Runner {
}
/**
 * ExecutionReviewChecker answers whether a task has at least one
 * execution_review comment authored by the agent. Wired via
 * SetExecutionReviewChecker; node.go adapts internal/comments.Store to
 * this shape so the task package stays free of a comments import.
 */
export type ExecutionReviewChecker = any;
/**
 * runtimeKnobs is the decoded form of resolver.ResolveAll output used by the
 * runner. Keeping it in a struct instead of reaching into the map on every
 * line in Execute makes the flow above readable and keeps each knob's fallback
 * semantics localized in decodeRuntimeKnobs.
 */
/**
 * retryCountKey is the settings-table key under which the runner persists the
 * number of retries already attempted for a task. Underscore prefix marks it
 * as internal runtime state (not a user-configurable knob in the catalog) —
 * the same convention used elsewhere in the repo for private keys.
 */
/**
 * pendingToolCall tracks a tool_use awaiting its tool_result.
 */

//////////
// source: runtime.go

/**
 * RuntimeState represents a persisted snapshot of a running task.
 */
export interface RuntimeState {
  task_id: string;
  marker: string;
  title: string;
  manifest: string;
  agent: string;
  pid: number /* int */;
  paused: boolean;
  actions: number /* int */;
  lines: number /* int */;
  last_line: string;
  started_at: string;
  updated_at: string;
}

//////////
// source: scheduler.go

/**
 * ManifestDepChecker checks if a manifest's dependencies are satisfied.
 * Implemented by node.Node to avoid circular imports.
 */
export type ManifestDepChecker = any;
/**
 * Scheduler checks for due tasks and fires them on a timer.
 */
export interface Scheduler {
}
/**
 * schedulerTickFloor is the minimum tick duration. Matches the catalog's
 * slider min; guards against a misconfigured knob that would DoS the DB.
 */

//////////
// source: settings_adapter.go

/**
 * SettingsAdapter implements settings.TaskLookup for the settings resolver.
 * It lives in internal/task (not internal/settings) so the settings package
 * stays free of a task import — the resolver needs only the minimal interface
 * declared in internal/settings/resolver.go.
 */
export interface SettingsAdapter {
  Store?: Store;
}

//////////
// source: status.go

/**
 * Status is the canonical lifecycle state of a task row.
 * This is a closed set of eight values. New code MUST use these constants
 * instead of literal strings so the compiler flags typos and downstream
 * exhaustive switches don't miss a case.
 */
export type Status = string;
/**
 * StatusPending — the task exists but has nothing arming it to fire.
 * No dependency, no schedule, no manual start. Stays here forever
 * unless the operator does one of those three things. New rows with
 * empty depends_on and no next_run_at land here.
 */
export const StatusPending: Status = "pending";
/**
 * StatusWaiting — the task has an unmet dependency and will auto-fire
 * when its parent task reaches StatusCompleted. Written by
 * Store.Create when depends_on is set and the parent isn't done, and
 * by the scheduler when it dequeues a task whose dep has regressed.
 * Distinct from Pending: Waiting participates in auto-activation,
 * Pending does not.
 */
export const StatusWaiting: Status = "waiting";
/**
 * StatusScheduled — armed for execution. The scheduler's dequeue
 * query picks up rows in this state where next_run_at <= now.
 */
export const StatusScheduled: Status = "scheduled";
/**
 * StatusRunning — agent subprocess is live.
 */
export const StatusRunning: Status = "running";
/**
 * StatusPaused — running process has been SIGSTOP'd by the operator
 * and can be resumed. Distinct from Scheduled: a paused task is
 * mid-execution with a live PID, not queued.
 */
export const StatusPaused: Status = "paused";
/**
 * StatusCompleted — agent exited and the watcher audit either passed
 * or returned a warning (warnings don't downgrade). Terminal unless
 * the watcher subsequently downgrades to Failed.
 */
export const StatusCompleted: Status = "completed";
/**
 * StatusFailed — agent exited with error, hit the cost cap, timed
 * out, OR was downgraded from Completed by a failing watcher audit.
 * Terminal.
 */
export const StatusFailed: Status = "failed";
/**
 * StatusCancelled — operator called task_cancel from any pre-terminal
 * state. Terminal.
 */
export const StatusCancelled: Status = "cancelled";

//////////
// source: store.go

/**
 * Task represents scheduled work against a manifest.
 */
export interface Task {
  id: string;
  marker: string;
  manifest_id: string;
  title: string;
  description: string;
  schedule: string; // "once", "5m", "1h", cron expression
  /**
   * Status is one of the 8 canonical lifecycle states defined in
   * status.go: pending, waiting, scheduled, running, paused, completed,
   * failed, cancelled. See status.go's validTransitions map for the
   * allowed edges of the state machine. Writes go through
   * Store.UpdateStatus, which validates transitions and rejects
   * illegal moves.
   */
  status: string;
  agent: string; // agent type: claude-code, cursor, etc.
  source_node: string;
  created_by: string; // session or dashboard
  depends_on: string; // task ID that must complete before this runs
  block_reason: string; // reason task is blocked (e.g. manifest dependency)
  run_count: number /* int */;
  last_run_at: string;
  next_run_at: string;
  last_output: string;
  created_at: string;
  updated_at: string;
  /**
   * Computed from task_runs — populated by enrichWithCosts()
   */
  total_turns: number /* int */;
  total_cost: number /* float64 */;
}
/**
 * TaskRun represents a single execution of a task, preserving history.
 */
export interface TaskRun {
  id: number /* int */;
  task_id: string;
  run_number: number /* int */;
  output: string;
  status: string;
  actions: number /* int */;
  lines: number /* int */;
  cost_usd: number /* float64 */;
  turns: number /* int */;
  input_tokens: number /* int */;
  output_tokens: number /* int */;
  cache_read_tokens: number /* int */;
  cache_create_tokens: number /* int */;
  model: string;
  pricing_version: string;
  /**
   * Host-metrics summary. Full time-series on task_run_host_samples,
   * fetched separately for the Run Stats sparkline overlay.
   */
  peak_cpu_pct: number /* float64 */;
  avg_cpu_pct: number /* float64 */;
  peak_rss_mb: number /* float64 */;
  started_at: string;
  completed_at: string;
}
/**
 * Store manages task persistence.
 */
export interface Store {
}
/**
 * taskColumns is the standard column list for task SELECT queries.
 */

//////////
// source: workspace.go

/**
 * workspaceRoot is the default directory under the repo where per-task
 * worktrees live. Kept inside the repo (not /tmp) so disk layout is
 * predictable and the operator can inspect a stuck task's workspace
 * without hunting. Overridable via the `worktree_base_dir` knob which
 * may be absolute (out-of-tree) or relative (joined onto the repo dir).
 */
