// Code generated by tygo. DO NOT EDIT.
// GENERATED FILE — DO NOT EDIT. Run `make types` to regenerate from Go.

//////////
// source: delusion.go

/**
 * Delusion represents an agent deviating from a manifest — going off-spec.
 */
export interface Delusion {
  id: number /* int */;
  session_id: string;
  source_node: string;
  action_id: string;
  task_id: string;
  manifest_id: string;
  manifest_marker: string;
  manifest_title: string;
  tool_name: string;
  tool_input: string;
  score: number /* float64 */; // inverse — lower similarity to manifest = higher delusion
  reason: string; // why it was flagged
  status: string; // flagged, confirmed, dismissed
  created_at: string;
}

//////////
// source: dependencies.go

/**
 * Dep is the denormalized row the UI + MCP callers want when listing
 * deps or dependents: id + marker + title + current status are enough to
 * render a row without a second lookup per entry.
 */
export interface Dep {
  id: string;
  marker: string;
  title: string;
  status: string;
  created_at: string;
  created_by: string;
}

//////////
// source: links.go

/**
 * Link represents a many-to-many relationship between an idea and a manifest.
 */
export interface Link {
  id: number /* int */;
  idea_id: string;
  idea_marker: string;
  manifest_id: string;
  manifest_marker: string;
  created_at: string;
}
/**
 * IdeaRef is a lightweight idea reference shown on manifest detail.
 */
export interface IdeaRef {
  id: string;
  marker: string;
  title: string;
  status: string;
}
/**
 * ManifestRef is a lightweight manifest reference shown on idea detail.
 */
export interface ManifestRef {
  id: string;
  marker: string;
  title: string;
  status: string;
}

//////////
// source: settings_adapter.go

/**
 * SettingsAdapter implements settings.ManifestLookup for the settings resolver.
 * Like its task counterpart it lives outside internal/settings to preserve the
 * import-cycle boundary — the resolver only references the minimal interface
 * declared in internal/settings/resolver.go.
 */
export interface SettingsAdapter {
  Store?: Store;
}

//////////
// source: store.go

/**
 * Manifest is a detailed development spec document.
 */
export interface Manifest {
  id: string;
  marker: string;
  title: string;
  description: string; // one-liner
  content: string; // full markdown spec
  status: string; // draft, open, closed, archive
  jira_refs: string[]; // e.g. ["ENG-4816", "ENG-5266"]
  tags: string[];
  author: string; // session that created it
  source_node: string;
  project_id: string; // optional project grouping
  depends_on: string; // comma-separated manifest IDs
  version: number /* int */;
  created_at: string;
  updated_at: string;
  /**
   * Computed from linked tasks — populated by EnrichWithCosts()
   */
  total_tasks: number /* int */;
  total_turns: number /* int */;
  total_cost: number /* float64 */;
}
/**
 * Store manages manifest persistence.
 */
export interface Store {
}
