// Code generated by tygo. DO NOT EDIT.


//////////
// source: store.go

export const EventStarted = "started";
export const EventSample = "sample";
export const EventCompleted = "completed";
export const EventFailed = "failed";
export const EventTurn = "turn"; // one row per turn boundary; Turns field holds the turn number
/**
 * Terminal-reason values populated on terminal (completed/failed) rows.
 * Used for pass-rate classification — see PassRateByEntity. ProcessError /
 * BuildFail / DeliverableMissing are referenced by the runner's retry and
 * proposer-trigger paths as classification inputs; expose them here so those
 * call sites read from the canonical constant rather than re-declaring strings.
 */
export const TerminalReasonSuccess = "success";
/**
 * Terminal-reason values populated on terminal (completed/failed) rows.
 * Used for pass-rate classification — see PassRateByEntity. ProcessError /
 * BuildFail / DeliverableMissing are referenced by the runner's retry and
 * proposer-trigger paths as classification inputs; expose them here so those
 * call sites read from the canonical constant rather than re-declaring strings.
 */
export const TerminalReasonMaxTurns = "max_turns";
/**
 * Terminal-reason values populated on terminal (completed/failed) rows.
 * Used for pass-rate classification — see PassRateByEntity. ProcessError /
 * BuildFail / DeliverableMissing are referenced by the runner's retry and
 * proposer-trigger paths as classification inputs; expose them here so those
 * call sites read from the canonical constant rather than re-declaring strings.
 */
export const TerminalReasonTimeout = "timeout";
/**
 * Terminal-reason values populated on terminal (completed/failed) rows.
 * Used for pass-rate classification — see PassRateByEntity. ProcessError /
 * BuildFail / DeliverableMissing are referenced by the runner's retry and
 * proposer-trigger paths as classification inputs; expose them here so those
 * call sites read from the canonical constant rather than re-declaring strings.
 */
export const TerminalReasonProcessError = "process_error";
/**
 * Terminal-reason values populated on terminal (completed/failed) rows.
 * Used for pass-rate classification — see PassRateByEntity. ProcessError /
 * BuildFail / DeliverableMissing are referenced by the runner's retry and
 * proposer-trigger paths as classification inputs; expose them here so those
 * call sites read from the canonical constant rather than re-declaring strings.
 */
export const TerminalReasonBuildFail = "build_fail";
/**
 * Terminal-reason values populated on terminal (completed/failed) rows.
 * Used for pass-rate classification — see PassRateByEntity. ProcessError /
 * BuildFail / DeliverableMissing are referenced by the runner's retry and
 * proposer-trigger paths as classification inputs; expose them here so those
 * call sites read from the canonical constant rather than re-declaring strings.
 */
export const TerminalReasonDeliverableMissing = "deliverable_missing";
/**
 * Row is one append-only event row in execution_log.
 */
export interface Row {
  id: string;
  run_uid: string;
  entity_uid: string;
  event: string;
  run_number: number /* int */;
  trigger: string;
  node_id: string;
  terminal_reason: string;
  started_at: number /* int64 */;
  completed_at: number /* int64 */;
  cancelled_at: number /* int64 */;
  cancelled_by: string;
  duration_ms: number /* int64 */;
  ttfb_ms: number /* int64 */;
  exit_code: number /* int */ | null;
  error: string;
  provider: string;
  model: string;
  model_context_size: number /* int */;
  agent_runtime: string;
  agent_version: string;
  pricing_version: string;
  input_tokens: number /* int64 */;
  output_tokens: number /* int64 */;
  cache_read_tokens: number /* int64 */;
  cache_create_tokens: number /* int64 */;
  reasoning_tokens: number /* int64 */;
  tool_use_tokens: number /* int64 */;
  cost_usd: number /* float64 */;
  estimated_cost_usd: number /* float64 */;
  cache_savings_usd: number /* float64 */;
  cache_hit_rate_pct: number /* float64 */;
  context_window_pct: number /* float64 */;
  cost_per_turn: number /* float64 */;
  cost_per_action: number /* float64 */;
  tokens_per_turn: number /* float64 */;
  turns: number /* int */;
  actions: number /* int */;
  errors: number /* int */;
  compactions: number /* int */;
  parallel_tasks: number /* int */;
  tool_calls_json: string;
  lines_added: number /* int */;
  lines_removed: number /* int */;
  files_changed: number /* int */;
  commits: number /* int */;
  pr_number: number /* int */ | null;
  branch: string;
  commit_sha: string;
  worktree_path: string;
  cpu_pct: number /* float64 */;
  rss_mb: number /* float64 */;
  disk_used_gb: number /* float64 */;
  peak_cpu_pct: number /* float64 */;
  avg_cpu_pct: number /* float64 */;
  peak_rss_mb: number /* float64 */;
  avg_rss_mb: number /* float64 */;
  net_rx_mbps: number /* float64 */;
  net_tx_mbps: number /* float64 */;
  disk_read_mbps: number /* float64 */;
  disk_write_mbps: number /* float64 */;
  mem_used_mb: number /* float64 */;
  mem_total_mb: number /* float64 */;
  load_avg_1m: number /* float64 */;
  created_by: string;
  created_at: string;
  session_id: string; // Claude Code / MCP session that generated this row
  tests_run: number /* int */;
  tests_passed: number /* int */;
  tests_failed: number /* int */;
  agent_pid: number /* int */; // OS PID of the spawned agent process; 0 if unknown
}
/**
 * PassRateSummary aggregates terminal execution-log rows for one entity.
 * TotalRuns == 0 means the entity has never run — callers must check this
 * before treating PassRate as meaningful.
 */
export interface PassRateSummary {
  EntityUID: string;
  TotalRuns: number /* int */;
  SuccessRuns: number /* int */;
  FailedRuns: number /* int */;
  MaxTurnsRuns: number /* int */;
  TimeoutRuns: number /* int */;
  AvgTurns: number /* float64 */;
  AvgCostUSD: number /* float64 */;
  PassRate: number /* float64 */; // SuccessRuns / TotalRuns; 0.0 when TotalRuns == 0
}
/**
 * OutputChunk is one live text chunk in execution_output.
 */
export interface OutputChunk {
  id: string;
  run_uid: string;
  seq: number /* int */;
  chunk: string;
  created_by: string;
  created_at: string;
}
/**
 * Store owns the execution_log and execution_output tables.
 */
export interface Store {
}
/**
 * InFlightRun holds the minimal fields needed for zombie-process detection.
 */
export interface InFlightRun {
  RunUID: string;
  EntityUID: string;
  AgentPID: number /* int */;
}

//////////
// source: store.go

export const TypeSkill = "skill";
export const TypeProduct = "product";
export const TypeManifest = "manifest";
export const TypeTask = "task";
export const TypeIdea = "idea";
export const TypeRAG = "RAG";
export const StatusDraft = "draft";
export const StatusActive = "active";
export const StatusClosed = "closed";
export const StatusArchived = "archived";
/**
 * Entity is a single SCD-2 version row for any first-class OpenPraxis object.
 * The "current" row for an entity_uid is the one where valid_to = ''.
 */
export interface Entity {
  row_id: number /* int64 */;
  entity_uid: string;
  type: string;
  title: string;
  status: string;
  tags: string[];
  valid_from: string;
  valid_to: string;
  changed_by: string;
  change_reason: string;
  created_at: string;
}
/**
 * Store manages entity persistence using SCD-2 semantics.
 */
export interface Store {
}

//////////
// source: store.go

/**
 * Action represents a single tool call by an agent session.
 */
export interface Action {
  id: string;
  session_id: string;
  source_node: string;
  task_id: string;
  tool_name: string;
  tool_input: string;
  tool_response: string;
  cwd: string;
  turn_number: number /* int */; // agent turn this action belongs to; 0 = pre-feature
  created_at: string;
}
/**
 * Store manages action persistence in SQLite.
 */
export interface Store {
}

//////////
// source: types.go

export type CommentType = string;
/**
 * TypePrompt is the active prompt/instructions for an entity.
 * Append-only; the latest revision is the current prompt.
 */
export const TypePrompt: CommentType = "prompt";
/**
 * TypeComment is everything else — notes, findings, decisions,
 * review results, execution summaries, watcher output.
 */
export const TypeComment: CommentType = "comment";
/**
 * Legacy aliases kept so old data and any stragglers compile.
 * All resolve to TypeComment except description_revision → TypePrompt.
 */
export const TypeExecutionReview = TypeComment;
export const TypeUserNote = TypeComment;
export const TypeWatcherFinding = TypeComment;
export const TypeAgentNote = TypeComment;
export const TypeDecision = TypeComment;
export const TypeLink = TypeComment;
export const TypeReviewRejection = TypeComment;
export const TypeReviewApproval = TypeComment;
export const TypeDescriptionRevision = TypePrompt;
export interface CommentTypeInfo {
  type: CommentType;
  label: string;
  description: string;
  include_in_prompt_context: boolean;
}
