package comments

import (
	"database/sql"
	"fmt"
	"strings"
)

// InitSchema creates the comments table and its indexes on the given DB.
// Safe to call repeatedly; uses IF NOT EXISTS semantics.
//
// The caller is responsible for opening the DB with WAL mode and
// busy_timeout=5000 (see visceral rule #10 — SQLite must always use
// WAL + busy_timeout=5000 on every db.Open).
//
// The `id` column is a UUID v7 string generated by the caller (Store.Add).
// `created_at` / `updated_at` are unix seconds. `parent_id` is reserved
// for threaded replies in a future iteration and is not populated in M1.
func InitSchema(db *sql.DB) error {
	_, err := db.Exec(`CREATE TABLE IF NOT EXISTS comments (
		id           TEXT NOT NULL PRIMARY KEY,
		target_type  TEXT NOT NULL CHECK (target_type IN ('entity')),
		target_id    TEXT NOT NULL,
		author       TEXT NOT NULL,
		type         TEXT NOT NULL,
		body         TEXT NOT NULL,
		created_at   INTEGER NOT NULL,
		updated_at   INTEGER,
		parent_id    TEXT
	)`)
	if err != nil {
		return fmt.Errorf("create comments table: %w", err)
	}

	// Migrate legacy per-type target_type values → 'entity'.
	// Runs as a no-op on fresh DBs and on DBs already migrated.
	if err := migrateTargetTypeToEntity(db); err != nil {
		return fmt.Errorf("migrate target_type to entity: %w", err)
	}

	// Collapse legacy comment types → 'prompt' or 'comment'.
	if err := migrateCollapseTypes(db); err != nil {
		return fmt.Errorf("migrate collapse comment types: %w", err)
	}

	_, err = db.Exec(`CREATE INDEX IF NOT EXISTS idx_comments_target ON comments(target_type, target_id, created_at DESC)`)
	if err != nil {
		return fmt.Errorf("create comments target index: %w", err)
	}

	_, err = db.Exec(`CREATE INDEX IF NOT EXISTS idx_comments_author ON comments(author)`)
	if err != nil {
		return fmt.Errorf("create comments author index: %w", err)
	}

	return nil
}

// migrateTargetTypeToEntity rewrites all legacy per-type target_type values
// (product, manifest, task, idea) to 'entity' and rebuilds the table with a
// tightened CHECK constraint. Idempotent — a no-op when the DDL already only
// allows 'entity'.
func migrateTargetTypeToEntity(db *sql.DB) error {
	var ddl string
	if err := db.QueryRow(`SELECT sql FROM sqlite_master WHERE type='table' AND name='comments'`).Scan(&ddl); err != nil {
		return fmt.Errorf("read table ddl: %w", err)
	}
	// Already on the clean schema?
	if !strings.ContainsAny(ddl, "product") && strings.Contains(ddl, "'entity'") {
		return nil
	}

	tx, err := db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	// Rebuild with legacy values coerced to 'entity' in one pass.
	if _, err := tx.Exec(`CREATE TABLE comments_new (
		id           TEXT NOT NULL PRIMARY KEY,
		target_type  TEXT NOT NULL CHECK (target_type IN ('entity')),
		target_id    TEXT NOT NULL,
		author       TEXT NOT NULL,
		type         TEXT NOT NULL,
		body         TEXT NOT NULL,
		created_at   INTEGER NOT NULL,
		updated_at   INTEGER,
		parent_id    TEXT
	)`); err != nil {
		return fmt.Errorf("create comments_new: %w", err)
	}
	if _, err := tx.Exec(`INSERT INTO comments_new
		SELECT id, 'entity', target_id, author, type, body, created_at, updated_at, parent_id
		FROM comments`); err != nil {
		return fmt.Errorf("copy rows: %w", err)
	}
	if _, err := tx.Exec(`DROP TABLE comments`); err != nil {
		return fmt.Errorf("drop old: %w", err)
	}
	if _, err := tx.Exec(`ALTER TABLE comments_new RENAME TO comments`); err != nil {
		return fmt.Errorf("rename: %w", err)
	}
	return tx.Commit()
}

// migrateCollapseTypes rewrites legacy type values to the two canonical
// types: 'prompt' (was 'description_revision') and 'comment' (everything
// else). Idempotent — rows already at 'prompt' or 'comment' are untouched.
func migrateCollapseTypes(db *sql.DB) error {
	if _, err := db.Exec(`UPDATE comments SET type = 'prompt'  WHERE type = 'description_revision'`); err != nil {
		return fmt.Errorf("migrate type prompt: %w", err)
	}
	if _, err := db.Exec(`UPDATE comments SET type = 'comment' WHERE type NOT IN ('prompt', 'comment')`); err != nil {
		return fmt.Errorf("migrate type comment: %w", err)
	}
	return nil
}
