package comments

import (
	"database/sql"
	"fmt"
)

// InitSchema creates the comments table and its indexes on the given DB.
// Safe to call repeatedly; uses IF NOT EXISTS semantics.
//
// The caller is responsible for opening the DB with WAL mode and
// busy_timeout=5000 (see visceral rule #10 — SQLite must always use
// WAL + busy_timeout=5000 on every db.Open).
//
// The `id` column is a UUID v7 string generated by the caller (Store.Add).
// `created_at` / `updated_at` are unix seconds. `parent_id` is reserved
// for threaded replies in a future iteration and is not populated in M1.
func InitSchema(db *sql.DB) error {
	_, err := db.Exec(`CREATE TABLE IF NOT EXISTS comments (
		id           TEXT NOT NULL PRIMARY KEY,
		target_type  TEXT NOT NULL CHECK (target_type IN ('product','manifest','task')),
		target_id    TEXT NOT NULL,
		author       TEXT NOT NULL,
		type         TEXT NOT NULL,
		body         TEXT NOT NULL,
		created_at   INTEGER NOT NULL,
		updated_at   INTEGER,
		parent_id    TEXT
	)`)
	if err != nil {
		return fmt.Errorf("create comments table: %w", err)
	}

	_, err = db.Exec(`CREATE INDEX IF NOT EXISTS idx_comments_target ON comments(target_type, target_id, created_at DESC)`)
	if err != nil {
		return fmt.Errorf("create comments target index: %w", err)
	}

	_, err = db.Exec(`CREATE INDEX IF NOT EXISTS idx_comments_author ON comments(author)`)
	if err != nil {
		return fmt.Errorf("create comments author index: %w", err)
	}

	return nil
}
